Kuba\UserBundle\Form\Model\Registration:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        email:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 50
    getters:
        passwordMatchingUsername:
            - "False": { message: "The password cannot match your Username" }